POST http://localhost:3000/client HTTP/1.1
Content-Type: application/json

{
  "name": "Jonh Doe",
  "email": "jonh@mail.com"
}

###

POST http://localhost:3000/account HTTP/1.1
Content-Type: application/json

{
  "client_id": "ee4520b2-5c59-43bb-9fd6-4b98e2fc3083"
}


###

POST http://localhost:3000/transaction HTTP/1.1
Content-Type: application/json

{
  "account_id_from": "9878c6a6-1e8a-4e38-b243-2352d97a0b96",
  "account_id_to": "f636fda1-71cf-4064-ad93-b0fbe6146961",
  "amount": 50
}
