version: '3.8'

services:
  app:
    build: .
    container_name: node-keycloak
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
