name: ci-golang-workflow

on:
  push:
    branches: [feat/23-project, feat/develop-23-project]

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - run: go test
      - run: go run math.go
