name: ci-golang-workflow

on:
  pull_request:
    branches:
      - feat/develop-23-project

jobs:
  check-application:
    strategy:
      matrix:
        go-version: ['1.19', '1.20']
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: go test
      - run: go run math.go
